#
# [1]: "CIFAR10-DVS: An Event-Stream Dataset for Object Classification"
# Hongmin Li, Hanchao Liu, Xiangyang Ji, Guoqi Li, Luping Shi
#
#
dataset: DVS_CIFAR10
event_type: True
batch_size: 500
num_clss: 10
output_dimension: 10
time_window: 1000
spatial_ds_factor: 0.25
learning_rate: 0.001
train_size: 900 # Default 90% used for training in seminal paper [1]
test_size: 100 # Default 10% used for test in seminal paper [1]
pool_type: AvgPool

################################################################################
################################################################################

spk_cnn_arch_1:
  inp_lyr:
    inp_chnls: 2
    inp_dmx: 32
    inp_dmy: 32

  #########################

  conv_lyr_1:
    otp_chnls: 16
    krnl_size: 3

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  dense_lyr_1: 128
  dense_lyr_2: 64

################################################################################
################################################################################

spk_cnn_arch_2:
  inp_lyr:
    inp_chnls: 2
    inp_dmx: 32
    inp_dmy: 32

  #########################

  conv_lyr_1:
    otp_chnls: 32
    krnl_size: 7
    drpt_prob: 0.1

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_2:
    otp_chnls: 32
    krnl_size: 5
    drpt_prob: 0.1

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  dense_lyr_1: 512
  dense_lyr_2: 128

################################################################################
################################################################################

spk_cnn_arch_3:
  inp_lyr:
    inp_chnls: 2
    inp_dmx: 32
    inp_dmy: 32

  #########################

  conv_lyr_1:
    otp_chnls: 48
    krnl_size: 5

    stride: 1
    pool_size: 2

    #stride: 2
  #########################

  conv_lyr_2:
    otp_chnls: 64
    krnl_size: 3
    drpt_prob: 0.1

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_3:
    otp_chnls: 128
    krnl_size: 3
    drpt_prob: 0.2

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  dense_lyr_1: 512
  dense_lyr_2: 256

################################################################################
################################################################################

spk_cnn_arch_4:
  inp_lyr:
    inp_chnls: 2
    inp_dmx: 32
    inp_dmy: 32

  #########################

  conv_lyr_1:
    otp_chnls: 24
    krnl_size: 3
    stride: 1

  #########################

  conv_lyr_2:
    otp_chnls: 24
    krnl_size: 3
    drpt_prob: 0.1

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_3:
    otp_chnls: 48
    krnl_size: 3
    drpt_prob: 0.2

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_4:
    otp_chnls: 48
    krnl_size: 3
    drpt_prob: 0.3

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  dense_lyr_1: 256
  dense_lyr_2: 128

################################################################################
################################################################################

spk_cnn_arch_5:
  inp_lyr:
    inp_chnls: 2
    inp_dmx: 32
    inp_dmy: 32

  #########################

  conv_lyr_1:
    otp_chnls: 64
    krnl_size: 3
    stride: 1

  #########################

  conv_lyr_2:
    otp_chnls: 64
    krnl_size: 3
    drpt_prob: 0.1

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_3:
    otp_chnls: 128
    krnl_size: 3
    drpt_prob: 0.2

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  conv_lyr_4:
    otp_chnls: 128
    krnl_size: 3
    drpt_prob: 0.3

    stride: 1
    pool_size: 2

    #stride: 2

  #########################

  dense_lyr_1: 1024
  dense_lyr_2: 1024
################################################################################
################################################################################
